import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono, Playfair_Display } from 'next/font/google'
import './globals.css'
import { Provider } from './provider'
import { UserCoursesProvider } from '@/context/UserCoursesContext'
import { CourseProvider } from '@/context/useCourse'

const geistSans = Playfair_Display({
  variable: '--font-playfair_display',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Provider>
            <UserCoursesProvider>
              <CourseProvider>{children}</CourseProvider>
            </UserCoursesProvider>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}
